services:
  db:
    image: "postgres:16"
    container_name: db_demo
    environment:
      - POSTGRES_DB=shelter
      - POSTGRES_USER=mahi
      - POSTGRES_PASSWORD=admin123$
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"

  etl:
    container_name: etl_demo
    build: .
    #command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    command: https://raw.githubusercontent.com/mahendra-g-p/CSCI_5253_HomeWorks/main/Austin_Animal_Center_Outcomes.csv
    depends_on:
      - db 
        
        
        
volumes:
  db_data: